export default new Map([
  ['morte', 'Morte'],
  ['sangue', 'Sangue'],
  ['energia', 'Energia'],
  ['conhecimento', 'Conhecimento'],
  ['balistica', 'Balística'],
  ['corte', 'Corte'],
  ['eletricidade', 'Eletricidade'],
  ['fisico', 'Físico'],
  ['fogo', 'Fogo'],
  ['frio', 'Frio'],
  ['impacto', 'Impacto'],
  ['perfuracao', 'Perfuração'],
  ['fogo', 'Químico'],
])